services:
  db:
    image: postgres
    container_name: expense_db
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: expense
    volumes:
      - expense-data:/var/lib/postgresql
    
  api:
    image: expense-report:two-stage
    container_name: expense_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/expense
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    depends_on:
      - db

volumes:
  expense-data: